/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singlyLinkedLists;

public class Main {
    public static void main(String[] args) {

        /*
         Check if we add new Node to LinkedList correctly by call insert method of LinkedList class,
         and add a new Nodes to LinkedList class by insert method;
         But first we must create new object from LinkedList class.
         */
        LinkedList linkedList = new LinkedList();

        // Now use this new object from LinkedList class to use insert method, and give it an argument to nodeValue parameter.
        linkedList.insert(1);
        linkedList.insert(2);
        linkedList.insert(3);
        linkedList.insert(4);

        // Call includes to check if the value is exists in LinkedList or is not.
        System.out.println(linkedList.includes(5));
//        linkedList.includes(3);

        // To see the result we need to create a print function in LinkedList class, and call it here.
        System.out.println(linkedList.toString());
    }
}
